<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [2]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

In [7]:
df = pd.read_csv("/Users/mehuljangir/Code/Datasets/stanford-coursera/microchip.txt", header=None)

          0        1  2
0  0.051267  0.69956  1
1 -0.092742  0.68494  1
2 -0.213710  0.69225  1
3 -0.375000  0.50219  1
4 -0.513250  0.46564  1

In [15]:
x = list(df.iloc[:,0])
y = list(df.iloc[:,1])
qual = list(df.iloc[:,2])
for i in range(len(qual)):
    if qual[i] == '0':
        plt.plot(x, y, 'o')
        print('heheh')
#     else:
#         plt.plot(x, y, 'x')

1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0